// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY-_xqqlNA-QOcU2_2PYciOruFwuE_1eU',
    appId: '1:757134714165:android:b2d7301c80eaeb91d7187c',
    messagingSenderId: '757134714165',
    projectId: 'tripdna',
    storageBucket: 'tripdna.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNptonazdxa9vpAgSigyogyo_P903KmEE',
    appId: '1:757134714165:web:a2af4c5ea2ba0091d7187c',
    messagingSenderId: '757134714165',
    projectId: 'tripdna',
    authDomain: 'tripdna.firebaseapp.com',
    storageBucket: 'tripdna.firebasestorage.app',
    measurementId: 'G-N5L0P7TM3K',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYG37-pgRT_83hPjT7Q3ft88eEqF9jT7k',
    appId: '1:757134714165:ios:791d3ae7d2a5052dd7187c',
    messagingSenderId: '757134714165',
    projectId: 'tripdna',
    storageBucket: 'tripdna.firebasestorage.app',
    iosBundleId: 'com.example.tripdna',
  );

}